---
- name: Deploy Web Server
  hosts: webservers
  become: yes
  become_method: sudo
  tasks:
    - name: Install Apache
      package:
        name: apache2
        state: present

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create custom index.html
      copy:
        content: "Hello World from SJSU-{{ inventory_hostname[-1] }}"
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Open port 8080 in firewall
      ufw:
        rule: allow
        port: '8080'
        proto: tcp
        state: enabled
