---
- name: Deploy Web Server
  hosts: webservers
  become: yes
  become_method: sudo
  tasks:
    - name: Install Apache
      package:
        name: apache2
        state: present
      tags: deploy

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes
      tags: deploy

    - name: Create custom index.html
      copy:
        content: "Hello World from SJSU-{{ inventory_hostname[-1] }}"
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
      tags: deploy

    - name: Open port 8080 in firewall
      ufw:
        rule: allow
        port: '8080'
        proto: tcp
        state: enabled
      tags: deploy

- name: Undeploy Web Server
  hosts: webservers
  become: yes
  become_method: sudo
  tasks:
    - name: Stop Apache service
      service:
        name: apache2
        state: stopped
      tags: undeploy

    - name: Remove Apache package
      package:
        name: apache2
        state: absent
      tags: undeploy

    - name: Remove custom index.html
      file:
        path: /var/www/html/index.html
        state: absent
      tags: undeploy

    - name: Remove firewall rule for port 8080
      ufw:
        rule: deny
        port: '8080'
        proto: tcp
      tags: undeploy
